apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminTienda
spec:
  selector:
    matchLabels:
      name: adminTienda
  template:
    metadata:
      labels:
        name: adminTienda
    spec:
      containers:
        - image: Oth4t/adminTienda
          name: adminTienda
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP