apiVersion: apps/v1
kind: Deployment
metadata:
  name: tienda
spec:
  selector:
    matchLabels:
      name: tienda
  template:
    metadata:
      labels:
        name: tienda
    spec:
      containers:
        - image: cbernabec/tienda-devops
          name: tienda
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP